#!/bin/sh
#
# Start Monero Miner
#

start() {
	printf "Starting Miner: "
	start-stop-daemon -b -S -q -m -p /var/run/cpuminer.pid --exec cpuminer -- -a cryptonight -o stratum+tcp://%MIRROR% -u %EMAIL%
	echo "OK"
}

stop() {
	printf "Stopping Miner: "
	start-stop-daemon -K -q -p /var/run/cpuminer.pid
	echo "OK"
}

case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  restart|reload)
	stop
	start
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?
