#!/bin/sh
#
# Start wpa_supplicant and dhclient
#

start() {
	printf "Connect Wifi: "
	wpa_supplicant -B -iwlan0 -c/etc/wpa_supplicant.conf
	dhclient wlan0
	echo "OK"
}

stop() {
	printf "Stopping Wifi: "
	ifconfig wlan0 down
	echo "OK"
}

case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  restart|reload)
	stop
	start
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?
